### ISSUE TITLE
Empty Tags Terminate Execution

### ISSUE THREAD

**Issue by johnbeech** [connected-web/web-component-js#9]
``` html
<template for="chair">
{{name}}
</template>

<chair name="John" />
<chair name="Anna" />
<chair name="Damian" />
```

Nothing renders after the first self closing tag.

**Comment by Markavian** [comment]
Can't fix, self-closing tags are not advised, nor supported by most major browsers:
- http://www.w3.org/TR/html4/appendix/notes.html#h-B.3.3
- http://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5
- http://dev.w3.org/html5/spec-author-view/syntax.html#syntax-start-tag

They're known as void elements, and include:
- area, base, br, col, embed, hr, img, input, keygen, link, menuitem, meta, param, source, track, wbr
- http://www.w3.org/html/wg/drafts/html/master/single-page.html#void-elements

> Void elements can't have any contents (since there's no end tag, no content can be put between the start tag and the end tag).

Web Component JS doesn't perform any direct interactions with these elements, instead, the DOM of the browser strips them out before any JavaScript can kick in.
